Safecast/safecastapi

- .travis.yml
- config/database.yml.travis
Uses postgres 9.2 since that's what prod uses. Also uses postgis extension as documented in http://docs.travis-ci.com/user/using-postgresql/#Using-PostGIS
> Travis updates to get things running

- README.md
> Some doc updates from info provided by Rob

- .travis.yml
- Gemfile
- Gemfile.lock
- README.md
- circle.yml
- config/database.yml.ci
- spec/spec_helper.rb
Configured CircleCI closing #181, configured Code Climate, and added master branch badges.
Note: if we ever start using CircleCI in parallel it will [break](http://docs.codeclimate.com/article/220-help-im-having-trouble-with-test-coverage#fyis) Code Climate coverage monitoring.
> CI & Code Climate integration

- .gitignore
- Gemfile
- Gemfile.lock
- config/newrelic.yml
> New relic configuration

- app/controllers/bgeigie_imports_controller.rb
- app/models/bgeigie_import.rb
- app/views/bgeigie_imports/_head.html.erb
- config/locales/views/bgeigie_imports/en-US.yml
- config/routes.rb
Add button for forced processing
> Added process button for unprocessed files

- .travis.yml
- Gemfile
- spec/controllers/rails_admin/main_controller_spec.rb
- spec/fabricators/user_fabricator.rb
- spec/spec_helper.rb
This PR is part of #170. Also, related to #191 and #213 (need update rails before updating rails_admin).
Also, updated postgres to 9.3 in `.travis.yml` since https://github.com/Safecast/safecastapi/pull/253#issuecomment-218343304.
I would like to install this branch onto staging server. How can I do it?
> Update ruby to 2.0.0-p648

- lib/tasks/db.rake
This PR fixes [this build failure](https://travis-ci.org/Safecast/safecastapi/builds/135776014).
> Fix rubocop offences

- app/controllers/measurements_controller.rb
- app/models/measurement.rb
- spec/controllers/measurements_controller_spec.rb
- spec/fabricators/measurement_fabricator.rb
- spec/models/measurement_spec.rb
> Fix issue #249

- app/controllers/application_controller.rb
This PR should resolve #252
In developer mode, it shows `user_id`.
> Resolve #252

- Gemfile.lock
- app/views/kaminari/twitter-bootstrap/_paginator_without_count.html.erb
- app/views/layouts/_summarize_results.html.erb
- app/views/measurements/index.html.erb
- config/initializers/kaminari.rb
> Not issue count query in kaminari

- db/migrate/20160614042818_add_user_id_and_created_at_index_to_measurements.rb
- db/structure.sql
Should help speed up stuff like:
select * from measurements where user_id = 123 order by captured_at asc limit 1;
> Add index on measurements(user_id, created_at)

- app/controllers/measurements_controller.rb
I was surprised when I read document on https://github.com/gtd/csv_builder
> Add a comment about instance variables that are used in csvbuilder

- app/views/measurements/index.html.erb
- app/views/measurements/new.html.erb
- spec/acceptance/user_creates_new_measurement_spec.rb
> Fix issue #166

- app/controllers/application_controller.rb
- config/application.rb
- config/environments/production.rb
Source: https://github.com/department-of-veterans-affairs/caseflow-efolder/commit/c05730e5c0837c9c968ffdfac0fd83149a45e438
> Move ssl enforcement to controller so we can allow plain text json requests

- app/views/devise/passwords/new.html.erb
- spec/acceptance/user_tries_to_reset_password_spec.rb
https://rpm.newrelic.com/accounts/1057812/applications/10580222/traced_errors/10d8ee1-c6f2e18b-3853-11e6-8eb5-f8bc12425d4c
> Fix 'Missing Partial' error on password reset page

- .travis.yml
- Gemfile
> Update Ruby to 2.1.10

- app/assets/javascripts/application.js
This is one of issues on CodeClimate.
> Fix "Missing semicolon"

- app/views/bgeigie_imports/_delete.html.erb
- app/views/bgeigie_imports/_show.html.erb
- config/locales/views/bgeigie_imports/en-US.yml
- spec/acceptance/user_shows_bgeigie_import_spec.rb
This PR is for https://github.com/Safecast/safecastapi/pull/284#issuecomment-225486985
> Show delete import link only when user has rights to delete

- public/robots.txt
> Disallow robots

- app/mailers/notifications.rb
- spec/controllers/bgeigie_imports_controller_spec.rb
- spec/mailers/notifications_spec.rb
> Add spec bgeigie_imports#submit for PUT method

- app/controllers/profiles_controller.rb
- spec/acceptance/user_profile_spec.rb
- spec/controllers/profiles_controller_spec.rb
https://rpm.newrelic.com/accounts/1057812/applications/10580222/traced_errors/46b7931f-44d0-11e6-ac40-f8bc12425d4c_0_17649
> Fix Activemodel::ForbiddenAttributesError on ProfilesController#update

- app/controllers/profiles_controller.rb
- spec/acceptance/user_profile_spec.rb
- spec/controllers/profiles_controller_spec.rb
- spec/fabricators/user_fabricator.rb
> Fix issue that user cannot change password

- app/views/devise/mailer/reset_password_instructions.html.erb
- spec/acceptance/user_reset_password_spec.rb
https://safecast.slack.com/archives/api/p1472746207000002
> Fix issue that users cannot reset their password

- app/controllers/bgeigie_imports/not_approved_controller.rb
- app/controllers/bgeigie_imports/not_processed_controller.rb
- app/helpers/bgeigie_imports_helper.rb
- app/models/bgeigie_import.rb
- app/views/application/_stuck_drives.html.haml
- app/views/bgeigie_imports/not_approved/index.html.haml
- app/views/bgeigie_imports/not_processed/index.html.haml
- app/views/layouts/application.html.erb
- config/locales/views/bgeigie_imports/not_approved/en-US.yml
- config/locales/views/bgeigie_imports/not_approved/ja.yml
- config/locales/views/bgeigie_imports/not_processed/en-US.yml
- config/locales/views/bgeigie_imports/not_processed/ja.yml
- config/routes.rb
- spec/acceptance/user_views_bgeige_imports_not_approved_spec.rb
- spec/acceptance/user_views_bgeige_imports_not_processed_spec.rb
- spec/controllers/bgeigie_imports/not_approved_controller_spec.rb
- spec/controllers/bgeigie_imports/not_processed_controller_spec.rb
For #276 
This is an initial implementation of "stuck" drive views. Need more works like wording and such.
> Initial implementation of "stuck" drive views for moderators

- Gemfile
> Read ruby version from .ruby-version

- app/assets/javascripts/bgeigie_viewer.js
Visual/auto CPM/uSv/h and log CPM/cp5s separated.  Also add secondary
infowindow view with summary stats for logfile.
> Revise marker infowindow

- .travis.yml
Issue is https://github.com/travis-ci/travis-ci/issues/6972, worked around this in ingest for https://github.com/Safecast/ingest/commit/6d829422bb7b850562d764d0160ae2d78db11c2d
> Fix up travis postgis problem

- script/dump_measurements
Improved the readability of the script, added variables, comments. Plan to unify the other scripts.
No changed functionality (yet).
This was tested in AWS partially, I guess the only way is to deploy and see if it works in prod.
Connected to https://github.com/Safecast/safecastapi/issues/221
> Improve readability of the script

- Dockerfile.postgres
- docker-compose.yml
- lib/tasks/db.rake
```
$ docker build -f Dockerfile.postgres .
...
$ docker run <container ID> -p 5432:5432
```
You could use docker-compose.
```
$ docker-compose up
```
See `config/database.yml.sample` to use with.
> Add Dockerfile to build Postgresql 9.5 with postgis extension

- app/controllers/api_docs_controller.rb
> Fix basePath of swagger document

- config/database.yml.docker
- config/database.yml.local
For https://github.com/Safecast/safecastapi/pull/457
> Add a database config for docker

- app/views/home/show.html.erb
> Add better examples for measurements api

- app/views/bgeigie_imports/_static_metadata.html.erb
- config/locales/views/bgeigie_imports/en-US.yml
> Add "Highest measurement" on bGeigie import detail page

- config/database.yml.docker
This seems to work for me when using the included docker-compose on master. Tests pass and UI loads from rails server.
> Add a docker database config

- app/views/bgeigie_imports/_edit.html.erb
- app/views/measurements/new.html.erb
- config/locales/en-US.yml
- config/locales/ja.yml
Updated sensor height step from 1m to 0.1m. Hope I updated the right file...
Connected to #487
> Sensor height update

- Dockerfile.postgres
- docker-compose.yml
* Trust only from private networks in `pg_hba.conf`
* Bind to 127.0.0.1:5432
> Refactor postgresql container settings

- Dockerfile
- docker-compose.yml
This PR adds `Dockerfile` for application.
> Add Dockerfile for application

- app/controllers/bgeigie_imports_controller.rb
- app/models/bgeigie_import.rb
- app/views/layouts/application.html.erb
- spec/controllers/bgeigie_imports_controller_spec.rb
Connected to #131 
This PR should order bgeigie imports by creation date/time.
> Sort bgeigie imports by creation date/time

- app/controllers/bgeigie_imports_controller.rb
- app/models/bgeigie_import.rb
- app/views/layouts/application.html.erb
- spec/controllers/bgeigie_imports_controller_spec.rb
Reverts Safecast/safecastapi#501
Related to https://github.com/Safecast/safecastapi/issues/131
> Revert "Sort bgeigie imports by creation date/time"

- app/controllers/bgeigie_imports_controller.rb
- app/views/bgeigie_imports/_show.html.erb
- spec/controllers/bgeigie_imports_controller_spec.rb
> Disallow to delete approved bGeigie imports

- app/controllers/bgeigie_imports_controller.rb
- app/models/bgeigie_import.rb
- app/views/bgeigie_imports/index.html.erb
- db/migrate/20181130044638_add_approved_by_to_measurement_imports.rb
- db/structure.sql
- script/add_approved_by_column.sql
Script that adds a approved by column and fills it with a default value(Befor that feature) for every approved file so far.
Every approved file after that, will have the email of the moderator who approved it as the value.
> Approved by column

- app/models/measurement_import.rb
- spec/controllers/bgeigie_imports_controller_spec.rb
- spec/models/measurement_import_spec.rb
connected to https://github.com/Safecast/safecastapi/issues/486
The best way I came up with, is to change the message afterwards.
> Provide import ID after a Md5sum collision 

- app/controllers/radiation_index_controller.rb
- app/helpers/radiation_index_helper.rb
- app/views/layouts/application.html.erb
- app/views/radiation_index/radiation_index.erb
- config/routes.rb
- script/calculate_radiation_index
- script/radiation_index_export
- script/radiation_index_export.sql
Radiation index site requested by Pieter. 
radiation_index_export should be executed every week. There, data is pulled out of the database and the median/min/max- values are calculated so it can be displayed on the site.
> Radiation index

- script/imbrogno_daily_export
- script/imbrogno_export
connected to https://github.com/Safecast/safecastapi/issues/470
> Rsync added

- app/controllers/ingest_controller.rb
- app/models/ingest_measurement.rb
- app/views/ingest/index.html.erb
- app/views/layouts/application.html.erb
- config/database.yml
- config/locales/views/layouts/en-US.yml
- config/routes.rb
- spec/controllers/ingest_controller_spec.rb
- spec/models/ingest_measurment_spec.rb
What kind of filters do we need besides area?
Date and the field(for example: PM 2.5)? maybe some other?
> Ingest-data-View Hackathon 2018

- script/calculate_radiation_index
Calculating whiskers to get rid of outliers for the minimum and maximum calculation
> Radiation Index outliers fix

- Gemfile
- Gemfile.lock
- config/application.rb
Are we using [Skylight](https://skylight.io) ?
> Revome Skylight

- README.md
I always forget about ZenHub, so I would like to add badge on README.md.
https://www.zenhub.com/faq
> Add ZenHub badge

- .ebextensions/web.config
- .ebextensions/workers.config
Fixes https://github.com/Safecast/safecastapi/issues/550
> Set ELB & nginx timeout to 600s

- app/views/reminders/pending_imports.html.erb
> Add a bit of help text

- app/helpers/bgeigie_imports_helper.rb
- app/models/bgeigie_import.rb
- app/views/bgeigie_imports/_auto_approve_status.html.erb
- config/locales/views/bgeigie_imports/en-US.yml
All 5 auto approval rules ready
> Auto approve

- spec/controllers/rails_admin/main_controller_spec.rb
Going mildly nuclear here, but this test seems to fail roughly 50% of the time and is making deployments difficult so opening this as a possible option. Welcome to hear other options.
@eitoball & @auspicacious - let me know your thoughts
> Remove flakey test

- .ebextensions/swap.config
- .ebextensions/web.config
We had a few >1MB uploads come in but nginx defaults to 1M max
> Set nginx max body size to 10M

- app/controllers/bgeigie_imports/auto_approved_controller.rb
> remove unsubmitted drives from auto_approved link view

- config/initializers/rails_admin.rb
> Disable rails admin count bars

- app/controllers/users_controller.rb
https://safecast.slack.com/archives/C026F2Q1U/p1581328096277800
> Filter non-confirmed users

- Dockerfile
- cron.yaml
- cron/device_story_update_metadata
- db/migrate/20200131100913_add_more_columns_to_device_story_devices.rb
- db/structure.sql
For https://github.com/Safecast/safecastapi/pull/622
> A few tweaks

- app/models/bgeigie_import.rb
Now take everything after format= as version.
> version number which contains words now shows

- README.md
- README.ops.md
- docker-compose.yml
Also, make a couple of other fixes.
> Restrict docker-compose port exposure to localhost only

- .ebextensions/50-post-deploy.config
- .ebextensions/workers.config
Fixes https://github.com/Safecast/safecastapi/issues/645
Confirmed working on dev.
> Moved restarting the delayed job worker into a post-deploy script.

- config/locales/views/bgeigie_imports/ja.yml
> Translate drive delete link

- Gemfile
- config/application.rb
Reverts Safecast/safecastapi#677
> Revert "Switch elastic apm activation strategy"

- app/controllers/device_story/devices_controller.rb
- app/models/device_story/device.rb
- app/views/device_story/devices/index.html.erb
- config/routes.rb
- spec/controllers/davice_story/devices_controller_spec.rb
- spec/fabricators/device_story/device_fabricator.rb
@matschaffer  Not sure how it show looks like but here the basic UI that partially taken from @eitoball's PR https://github.com/Safecast/safecastapi/pull/642
> Add basic display to device story. Ref #606

- app/uploaders/file_uploader.rb
> Removed store_prefix from store_dir

- app/controllers/device_stories_controller.rb
- app/helpers/device_stories_helper.rb
- app/views/device_stories/index.html.erb
- app/views/device_stories/show.html.erb
- spec/helpers/device_stories_helper_spec.rb
Here's what I have right now. Tried to have a similar layout to the realtime website, but had to put the map below to make everything fit.
> Add Device Story show page

- app/controllers/device_stories_controller.rb
- app/helpers/device_stories_helper.rb
- app/models/device_story.rb
- app/views/device_stories/index.html.erb
- Refer to #606.
- Added search functionality via the "LIKE"-query.
- Added Elasticseach functionality which probably just works on my local database.
> Linkable search for the Device Story page

- app/assets/javascripts/application.js
- config/environments/production.rb
I got some warnings, plus noticed on prod it was issuing two requests on each keypress.
Thought I'd try this.
> Clean up the device story debounce

- app/assets/javascripts/application.js
Only printable characters and Backspace are triggering the search now.
> Narrow down search triggering keys

- app/views/bgeigie_imports/bgeigie_logs.kml.erb
Related #752 
This PR should be merged after merging #754
> Change to fetch icon files from api.safecast.org

- app/assets/stylesheets/application/safecast.scss
- app/views/bgeigie_imports/_head.html.erb
Basic banner added based on #780
> add support banner to b-geigie import

- app/assets/javascripts/application/device_story_graphs.js
- app/helpers/device_stories_helper.rb
- app/models/ingest_measurement.rb
- app/views/device_stories/show.html.erb
> Device story cpm other unit

- app/assets/stylesheets/application/safecast.scss
- app/controllers/measurements_controller.rb
- app/views/measurements/index.html.erb
> Change /measurements not to issue count query

- .github/codeql/codeql-config.yml
- .github/workflows/codeql-analysis.yml
[CodeQL](https://codeql.github.com) seems to be available as *beta*. I would like to try this to see if CodeQL helps to find vulnerabilities in our code.
> Create configuration file for CodeQL

- app/views/measurements/show.html.erb
- https://github.com/Safecast/safecastapi/security/code-scanning/1?query=ref%3Arefs%2Fheads%2Fmain
- https://github.com/Safecast/safecastapi/security/code-scanning/2?query=ref%3Arefs%2Fheads%2Fmain
> Fix code scanning alerts

- app/helpers/application_helper.rb
- app/views/layouts/application.html.erb
- config/routes.rb
> Add locale options to views

- app/assets/javascripts/device_stories.js
This PR fixes time range links in device story page that are added in #824.
> Fix time range links in device story page

- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
> Refactor Sign-up and Register forms

- app/helpers/device_stories_helper.rb
- app/models/device_story.rb
- app/views/device_stories/show.html.erb
- spec/helpers/device_stories_helper_spec.rb
> Add "Global Map" link to device story page

- app/models/bgeigie_import.rb
So we can support uploads like https://api.safecast.org/en-US/bgeigie_imports/49022
Also split out the very long header line so we can add comments for what each device they belong to. Cause I have no idea what most of them are :)
> Add header for 2.0.0CzechRad from Jan

- app/controllers/measurements_controller.rb
- app/models/measurement.rb
- app/views/measurements/new.html.erb
> Stop fetching last measurement when creating new measurement submission form

- app/views/ingest/index.html.erb
- Use bootstrap to style form
- Change form to keep submitted values
> Improve "Ingest Export" page

- config/initializers/kaminari_config.rb
> Limit kaminari pagination `per_page` to 1000

- app/assets/javascripts/application/open_all.js
There was migration error in #914
> Fix "Open All Unmoderated" button

- app/views/bgeigie_imports/index.html.erb
- config/locales/models/bgeigie_import.en-US.yml
- config/locales/models/bgeigie_import.ja.yml
- spec/acceptance/user_views_bgeigie_imports_spec.rb
Fixes errors like https://one.newrelic.com/nr1-core/errors/overview/MTA1NzgxMnxBUE18QVBQTElDQVRJT058MTA1ODAyMjI?account=1057812&duration=86400000&filters=%28domain%3D%27APM%27%20AND%20type%3D%27APPLICATION%27%29&state=12776f2e-303b-9e31-e380-5e13f7a059a1
> Fix sort by comment on bGeigie imports list

- app/controllers/users_controller.rb
- config/routes.rb
- spec/controllers/users_controller_spec.rb
> Add "GET /users/me" that returns current logged-in user information
