Safecast/safecastapi

- doc/.pgpass
We could also do a filter branch but I confirmed that this is not in use on dev, staging or prod so won't worry about that until after this is reviewed/merged.
Dev is the only environment with a `deploy` user, but this is not the password for that user.
Connected to #179
> Remove pgpass from repo tree

- lib/tasks/db.rake
This was originally added for the c66 staging setup, but seems to cause trouble locally, so I'll just drop it for now.
> Remove attempt to force postgis extension creation

- spec/spec_helper.rb
This way we don't see warnings when running specs locally.
> Wrap codeclimate init so we don't error if there's no token available

- README.md
> Fix link to  development instruction page for OS X

- Gemfile.lock
1.0.9.1 fixes some compilation errors On OS X 10.10. (See https://github.com/eventmachine/eventmachine/pull/668)
> Update eventmachine gem to 1.0.9.1

- config/initializers/postgis.rb
This PR changes to use `-i` option in `pg_dump` command only when `pg_dump` version is less than 9.0 because
1. From version 9.5, `pg_dump` returns error ("invalid option").
2. This option ( `-i` or `--ignore-version`) is "A deprecated option that is now ignored." in `pg_dump` version 9.[0-4].
> Use -i option when executing pg_dump if its version is less than 9.0.0

- .rspec
- Gemfile
- Gemfile.lock
- spec/acceptance/count_is_public_spec.rb
- spec/acceptance/guest_signs_up_spec.rb
- spec/acceptance/user_creates_a_device_spec.rb
- spec/acceptance/user_profile_spec.rb
- spec/acceptance/user_submits_reading_spec.rb
- spec/acceptance/user_uploads_bgeigie_log_spec.rb
- spec/acceptance/user_views_bgeige_imports_spec.rb
- spec/acceptance/user_views_their_measurements_spec.rb
- spec/controllers/bgeigie_logs_controller_spec.rb
- spec/controllers/rails_admin/main_controller_spec.rb
- spec/helpers/measurements_helper_spec.rb
- spec/integration/api/bgeigie_imports_spec.rb
- spec/integration/api/devices_spec.rb
- spec/integration/api/measurements_spec.rb
- spec/integration/api/users_spec.rb
- spec/mailers/notifications_spec.rb
- spec/models/admin_spec.rb
- spec/models/bgeigie_import_spec.rb
- spec/models/device_spec.rb
- spec/models/drive_import_spec.rb
- spec/models/drive_log_spec.rb
- spec/models/measurement_spec.rb
- spec/models/user_spec.rb
- spec/spec_helper.rb
This PR is related to #170. To update rails, I would like to have more coverages (~90%), so I added more specs and removed seems-to-be-unused code. Also, I updated rspec to 2.99.x.
~~I would like to review by someone who have more experience. Especially, these commits:~~
* ~~https://github.com/Safecast/safecastapi/commit/17f143319c806961ab9c9f2127fbf5d37ad77ec0~~
* ~~https://github.com/Safecast/safecastapi/commit/6cc345317647959e6c105a72c011940a2d2b1130~~
I removed methods that seem to be unused.
Also, I wrote specs for `DriveImport` and `DriveLog` models, but they seem to used for data migration purpose and not used now. Can I delete these models?
* https://github.com/Safecast/safecastapi/commit/1c8c66e8190a0b46340150ad20aa94acc902990b
* …
> Add specs for more coverages

- config/initializers/carrierwave.rb
`FileUploader` (app/uploader/file_uploader.rb) configures which storage to use. This file just configures Carrierwave. For test coverage purpose, it would be nice to configure even in test environment.
> Refactor Carrierwave initialization file

- app/models/measurement_import.rb
- db/migrate/20160607005457_alter_measurement_imports_subtype_set_not_null.rb
- db/structure.sql
- spec/controllers/bgeigie_imports_controller_spec.rb
- spec/models/bgeigie_import_spec.rb
This PR should fix #271 
When a `MeasurementImport` is created via `ActiveRecord`, AR seems to set unspecified columns to `NULL` (`nil`) explicitly, so I set subtype to 'None' when creating `MeasurementImport`.
This is `rails console` session in current master to show AR set `NULL` to unspecified columns.
```
[1] pry(main)> bi = BgeigieImport.create(cities: 'Tokyo', credits: 'John', source: File.open('spec/fixtures/bgeigie.log'), user_id: 1)
(1.6ms)  SELECT * FROM geometry_columns WHERE f_table_name='measurement_imports'
(0.1ms)  BEGIN
MeasurementImport Exists (0.9ms)  SELECT 1 AS one FROM "measurement_imports" W
HERE "measurement_imports"."md5sum" = 'aad36f9743753b490745c9656cd8fc79' LIMIT 1
(1.4ms)  SELECT * FROM geometry_columns WHERE f_table_name='users'
User Load (0.5ms)  SELECT …
```
> Fix issue 271

- app/controllers/bgeigie_imports_controller.rb
- spec/controllers/bgeigie_imports_controller_spec.rb
Currently, any login user can delete any bgeigie imports. Is this expected behavior? I thought that user can delete her/his imports and moderator can delete any imports, so I made this PR.
> Change BgeigieImportsController#destroy so that only owner or moderator can delete bgeigie import

- app/controllers/measurements_controller.rb
- spec/controllers/measurements_controller_spec.rb
API-Gateway posts JSON data like `{"longitude":"-70.872505","latitude":"42.812292","device_id":"99","value":"34","unit":"cpm","captured_at":"2016-06-20T13:14:00Z"}`. After updating to Rails 4, some parameters like `longitude` and `latitude` were not wrapped like `{ "measurement" : { "device_id":"99","value":"34","unit":"cpm","captured_at":"2016-06-20T13:14:00Z"}`. And this causes errors.
In `config/initializers/wrap_parameters.rb`, it is configured to wrap parameters if request is in JSON.
This PR change to define parameter names explicitly in `MeasurementsController`.
> Fix to wrap some measurement parameters in rails 4

- app/controllers/application_controller.rb
- spec/controllers/application_controller_spec.rb
It seems that condition (`ssl_enabled?`) to enable SSL access always returns `false`. This condition is expected to return `false` only when coming request is in JSON format.
Currently, we have
```ruby
force_ssl if: :ssl_enabled?
def ssl_enabled?
Rails.env.production? && !request.format.symbol == :json
end
```
but,
```pry
[1] pry(main)> !Mime::JSON.symbol == :json
=> false
[2] pry(main)> !Mime::HTML.symbol == :json
=> false
```
so, the `ssl_enabled?` always returns `false`.
> Fix condition for force_ssl and enable

- app/views/bgeigie_imports/_process_log.html.erb
- app/views/bgeigie_imports/_static_metadata.html.erb
Since we disallow web crawler robots access api, loading time of `bgeigie_imports#show` has been standing out on NewRelic. The breakdown of `BgeigieImportsController#show` (`bgeigie_imports#show`) shows that some view files taking long time. Inspecting those files and partial files, `#count` methods are called in some of files.
```
There's also the differences between `#count`, `#length`, and `#size` on
ActiveRecord::Relation. `#count` will always perform a count query,
`#length` will load up the records, and call `#length` on the resulting
array, and `#size` will do the smart thing based on whether or not we've
loaded. TLDR: use `#size`, unless you're calling it immediately before
you need to load the real records, in which case use `#length`. Never use
`#count`, since `#size` will skip …
```
> Use #size instead of #count on bgeigie_imports#show page

- config/locales/simple_form.en-US.yml
This PR is for #270
In this PR, descriptions are shown in the following.
And it can be done as @Frangible suggested in #270.
> Add help text for subtype on edit metadata page

- config/locales/en-US.yml
For some reason, I had this i18n problem back.
Therefore, I made some modifications in the i18n file. I kept the simple_form i18n file, and removed the following lines in the en-US file:
```
-      bgeigie_import:
-        create: Create Bgeigie import
-      device:
-        create: Create Device
```
I made a pull request for this as well.
Let me know if you think of a better solution.
(I think it's better to keep the simple_form i18n, and not merging it to the en_US, as it is the standard configuration for simple_form internationalization)
> I18n simple form issue

- README.md
Added links to Linux and Docker setup in the Readme.
Also modified the Linux setup : 
* added the following lines: 
```
#You can then run this command to avoid tracking the modificiation in the database.yml (and avoid pushing them in your next pull request - it would mess with other collaborators database settings).
git update-index --assume-unchanged config/database.yml
```
in order to avoid new linux collaborators to push their modified database.yml in their next pull request.
Let me know if you have any ideas on how to deal with this `script_dir` path issue between Mac and Linux (keeping in mind that Linux path contains Postgresql and Postgis version number, and must be adapted to each linux collaborators setup).
> add links to wiki pages Linux and Docket setup in the readme

- app/controllers/dashboards_controller.rb
- app/models/bgeigie_import.rb
- config/routes.rb
- spec/controllers/dashboards_controller_spec.rb
This is part of #406. This PR should exclude to count rejected drive from "Imports Awaiting Approval" on Dashboard.
> Exclude rejected drives from "Imports Awaiting Approval" count on Dashboard

- app/models/user.rb
We've refreshed the counter caches so we should be good for some time. Having this method means we can't display top users since it will time out attempting to actually count users with many measurements.
Connected to https://github.com/Safecast/safecastapi/issues/432
> Return counter cache for User#measurements_count

- app/models/measurement.rb
This PR is for #445. I thought that we should include `measurement_import_id` in `measurement` serialization.
> Add measurement_import_id in measurement serialization

- app/views/layouts/_datetime_picker.html.erb
Error in #446 seems to be caused because filter dialog creates date/time in MDY format (like "14/04/2018 12:34:56"). This PR change filter to create in ISO format (like "2018/04/14 12:34:56"). It has used MDY format since beginning. I wonder if it was working before...
> Format date/time in ISO format in filter dialog

- app/controllers/api_docs_controller.rb
- app/controllers/concerns/swagger_blocks/controllers/measurements.rb
- app/controllers/measurements_controller.rb
- app/models/concerns/swagger_blocks/models/measurement.rb
- app/models/concerns/swagger_blocks/models/measurement_input.rb
- app/models/measurement.rb
This PR adds Swagger documentation for measurement related API endpoints and model.
`/api_docs` should produce JSON document like in details.
Fixes https://github.com/Safecast/safecastapi/issues/440
<details>
```json
{"swagger":"2.0","info":{"version":"1.0.0","title":"Safecast API","description":"Safecast API","contact":{"name":"Safecast"}},"host":"api.safecast.org","basePath":"/api_docs","paths":{"/measurements":{"get":{"summary":"All Measurements","description":"Returns all measurements","responses":{"200":{"description":"measurement response","schema":{"type":"array","items":{"$ref":"#/definitions/Measurement"}}}}},"post":{"summary":"Add New Measurement","description":"Add a new measurement","parameters":[{"name":"measurement","in":"body","description":"Measurement to …
```
> Add Swagger document for measurements

- spec/controllers/bgeigie_imports_controller_spec.rb
Connected to #407.
b611473cf173c0658cdd185485686df962e7d390 is the only commit for this PR.
It adds a spec for bgeigie_import#reject to make sure bGeigie import without metadata can be rejected.
> Add spec for bgeigie_imports#reject

- spec/controllers/bgeigie_imports_controller_spec.rb
Based on recent test failures it seems the locale handling is a bit
non-deterministic in CI. I can't get it to fail locally, but since we
probably don't _need_ to assert locale info we'll just switch to a regex.
> Loosen up the assertion on session path

- db/structure.sql
I get error with `relation "schema_migrations" does not exist`.
```
$ docker-compose up -d
$ docker-compose exec -e 'DATABASE_URL=postgis://safecast:safecast@postgresql/safecast_development?schema_search_path=pubilc,postgis&encoding=unicode' app bundle exec rake db:drop db:create db:structure:load
...
psql:/src/db/structure.sql:1212: ERROR:  relation "schema_migrations" does not exist
LINE 1: INSERT INTO schema_migrations (version) VALUES ('20191023060...
^
psql:/src/db/structure.sql:1214: ERROR:  relation "schema_migrations" does not exist
LINE 1: INSERT INTO schema_migrations (version) VALUES ('20191025034...
^
GRANT
GRANT
```
```
$ docker-compose up -d
$ docker-compose exec -e 'DATABASE_URL=postgis://safecast:safecast@postgresql/safecast_development?schema_search_path=public,postgis&enc …
```
> Fix db/structure.sql

- .elasticbeanstalk/config.global.yml
eb cli seems to require it now, though we don't use it since the eb helper determines it based on ruby version
> Specify default platform in global config

- Dockerfile
This PR modifies `Dockerflie` to include `awscli` and `awsebcli`.
> Include aws tools in docker container image

- app/models/bgeigie_import.rb
Because this method was used in pre-refactored methods.
> Remove unused method

- cron.yaml
They've been bunching up lately (see https://grafana.safecast.cc/d/W7c552kZz/api-overview). Running the ios export every 8 hours should be okay per @Frangible 
Also adjusting the timing of the other jobs should help avoid them running before dump_measurements_ios is finished.
> Tune timing of export jobs

- Gemfile
- Gemfile.lock
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- config/environments/test.rb
- lib/tasks/pending_imports_reminder.thor
Newrelic - bundle update (for fixnum deprecation)
Simpleform - bundle update (for fixnum deprecation)
Pg - locked to 0.20 to avoid PGError warnings. Should upgrade when we get to Rails 5.x
Devise views, switched password edit & new to use simple form to avoid use of deprecated devise errors helper. Initially tried full view generation but led to a mess of errors on expected strings no longer being present.
Deliver warning, switched code
Static asset warning, switched code
Should look something like this now
> Remove deprecation warnings

- .circleci/config.yml
- .gitignore
- app/helpers/application_helper.rb
When loading a home page for the first time it defaults to `EN` while it should be `JP` because the default is `EN`
> Fix a default locate switcher

- config/application.rb
Currently, dev environment shows errors in the log that was introduced after adding `elastic-apm` gem (https://github.com/Safecast/safecastapi/pull/662):
```
app_1            | [ElasticAPM] Couldn't establish connection to APM Server:
app_1            | "#<HTTP::ConnectionError: failed to connect: Cannot assign requested address - connect(2) for \"localhost\" port 8200>"
app_1            | [ElasticAPM] Couldn't establish connection to APM Server:
app_1            | "#<HTTP::ConnectionError: failed to connect: Cannot assign requested address - connect(2) for \"localhost\" port 8200>"
app_1            | [ElasticAPM] Couldn't establish connection to APM Server:
app_1            | "#<HTTP::ConnectionError: failed to connect: Cannot assign requested address - connect(2) for \"localhost\" port …
```
> Enable elastic_apm for prod only

- Gemfile
- config/application.rb
This seems like the better option to avoid enabling it in dev environments while not using the deprecated `config.elastic_apm.active=`
> Switch elastic apm activation strategy

- bin/run_tests.bash
- docker-compose.yml
- docker_bin/run_test.bash
Default `RAILS_ENV` was added to [docker-compose](https://github.com/Safecast/safecastapi/blob/master/docker-compose.yml#L13) file and `rspec` was [running](https://github.com/Safecast/safecastapi/blob/master/spec/spec_helper.rb#L13) in `development` env. I assume this is why `RAILS_ENV` was [injected](https://github.com/Safecast/safecastapi/blob/master/docker_bin/run_test.bash#L3).
I think it makes sense to let `spec_helper.rb` set `RAILS_ENV`. 
What do you think?
> Remove explicit usage of RAILS_ENV

- config/environments/production.rb
Bringing back configs that were [accidentally removed](https://github.com/Safecast/safecastapi/commit/d73d3ceb87aa1350509e0c9a5d83a2a7231bcae3#diff-1d98f0039bbc6df92adee882ed99d993L67-L70) while upgrading to Rails 5.
> Fix Missing host to links

- app/views/dashboards/show.html.erb
`counter_cache` wasn't really used in the right place. Instead of using `#count`, it should be `#size` (or use `#measurements_count` directly) to avoid additional `SQL`
https://guides.rubyonrails.org/association_basics.html#options-for-belongs-to-counter-cache
```
[13] pry(main)> User.first.measurements.count
User Load (0.8ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1  [["LIMIT", 1]]
(9.5ms)  SELECT COUNT(*) FROM "measurements" WHERE "measurements"."user_id" = $1  [["user_id", 1]]
=> 46383
[14] pry(main)> User.first.measurements.size
User Load (0.5ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> 46383
```
@eitoball I saw you just closed your PR (https://github.com/Safecast/safecastapi/pull/556). Do you have time to review? …
> Use counter_cache

- bin/initialize_databases.bash
In some situations, the script would not work because `db:environment:set` was not being invoked.
> Fix init databases

- app/assets/stylesheets/application.css
- app/helpers/bgeigie_imports_helper.rb
- app/views/bgeigie_imports/_status.html.erb
- app/views/bgeigie_imports/index.html.erb
fixes #536 
Removed approved by/rejected by columns from table on bgeigie listing page. Approved/rejected information is on show page and is only viewable by moderators and uploader.
> Moved approved/rejected information from bgeigie listing to show page

- .ebextensions/web.config
Related to issue #648 
Based on research from @ZacharyCChang0828 
This will enable us to block IP addresses or CIDR ranges by modifying the `web.config` file and redeploying.
I have manually applied these changes in dev, so I know that the config works, but I'm not sure the `.ebextensions` syntax is correct.
Risks:
* Listing these IP address publicly could theoretically aid an attacker, but I'm not sure how.
* Using the real_ip module will change our logs; the AWS load balancer IP address will no longer show up in them. Instead, the request IP address will be the real one.
Follow-up tasks:
* We need to review and document what steps need to be taken to deploy an `.ebextensions` change. I'm not sure an ordinary deploy will do it.
* We should make the same changes to ingest.
> Added real IP and block IP functionality.

- app/models/measurement.rb
Fixes #535 
Removing the ordering by distance in nearby_to allows the table to be sorted by value.
> Fixed measurement sorting bug

- .ebextensions/aws.config
I would like to remove this because the same option setting (`ConnectionSettingIdleTimeout`) is in `.ebextensions/web.config`.
> Remove duplicated option settings in .ebextensions

- docker-compose.yml
When using docker-compose for development, some people (including me) were seeing port conflicts between Postgres servers already running on the host and the ports exposed by docker-compose for debugging.
With this change, you can set environment variables to override the ports.
Before accepting the PR, I should also update the documentation in https://github.com/Safecast/safecastapi/wiki/Dev:-Setup-on-Linux-and-OS-X-using-Docker
> Allowed user overrides of exposed docker-compose ports.

- app/controllers/bgeigie_imports_controller.rb
It seems that the freeform filter needs to be applied before other scopes, or it will break when used with those scopes. I found that combining `q` with scopes defined after it in the file worked, but not scopes defined before it.
> Reordering bgeigie_imports filtering to fix a bug with freeform queries

- app/assets/javascripts/application.js
- app/views/device_stories/_search_form.html.erb
Fixes #746
This occurs in Google Chrome and MicroSoft Edge, I think. It is because those browsers caches script contents, and they associate cached contents with histories.
> Fix not to cache script content for chromium-base browsers

- requirements.txt
Since 3.4, it uses rust compiler.
To fix [this problem](https://safecast.slack.com/archives/C026F2Q1U/p1613092646150100).
> Fix version of cryptography to 3.3.2

- app/models/device_story.rb
- app/safecast/tasks/device_stories/update_metadata.rb
- spec/safecast/tasks/device_stories/update_metadata_spec.rb
I noticed on http://tt.safecast.org/devices that note:dev:864475041086603 was showing up with a 0 lon/lat.
But the data has location info: https://grafana.safecast.cc/d/7wsttvxGk/safecast-airnote?orgId=1&var-device_urn=note:dev:864475041086603&from=now-3h&to=now
Figure we should probably just go ahead an import devices even ttserve can't tell us location info.
Note, I moved processing into the model to avoid the Metrics/MethodLength, Metrics/AbcSize issue.
Could also make it a helper function or something, but seemed reasonable to give DeviceStory a way to update itself from ttserve data.
Based on @rayozzie 's thoughts, maybe we can next work on an `update_from_elasticsearch` or something to reduce dependency on the ttserve API.
> Update device stories from 0 lon/lat

- .elasticbeanstalk/config.global.yml
- .gitignore
- Dockerfile
- Dockerfile.aws-cli
- docker-compose.yml
- requirements.txt
This PR create separate container image for AWS CLI and eb CLI.
To pass credential to container, you should use aws-vault. For example,
```
$ aws-valut exec safecast -- env | grep --color=no '^AWS_' > aws-cli.env
$ docker-compose --build aws-cli
...
```
> Create container image for AWS CLI and eb cli

- app/views/layouts/application.html.erb
This fixes safecast logo's link on mobile view reported by #788 .
> enable link to api.safecast.org on mobile view

- app/helpers/device_stories_helper.rb
- app/views/device_stories/show.html.erb
- spec/helpers/device_stories_helper_spec.rb
> Fix undefined method in device stories page

- .ebextensions/postgresql.config
- .ebextensions/workers.config
- .platform/hooks/predeploy/02_create_public_system_directory.sh
This PR fixes the following issues.
- No password in `.pgpass` because environment variables are not available
- Cause error when setting up `worker.config` in worker environment
- `public/system` is not available for new environment
Tried on [dev](https://github.com/Safecast/deployment-history/commit/6c84be0b99d7a5e58ad00e216236c1a89744d2ae), it seems to be working as expected.
> Fix for Amazon Linux 2 Platform

- cleartheworks.sh
This should help get us out of DB backlogs a little more easily.
I considered also trying to do this from the worker, but beanstalk doesn't get purge permissions by default. Plus the beanstalk worker would need keys to ssh into realtime and stop any processes there.
> Check in a clear out script

- app/controllers/crons_controller.rb
- spec/controllers/crons_controller_spec.rb
This PR is trying to prevent cron jobs from using database storages.
> Prevent from running multiple same cron jobs

- config/locales/cs-CZ.yml
- config/locales/pt.yml
*why*
There are translations in https://app.localeapp.com/projects/4489 which could be used. 
*what*
Add yaml files with translations in Czech and Portuguese to config/locales.
Rel: https://github.com/Safecast/safecastapi/issues/782
> Add czech and portuguese translations to locales

- spec/acceptance/user_profile_spec.rb
- spec/models/device_story_comment_spec.rb
Fixes #853
When locale is `:ja`, space between attribute name and message is removed.
TODO: i18n-ize error messages in `DeviceStoryComment`
> Reset to default locale

- cron/dump_measurements
Measurements `.csv` file gets fully generated at first with non-conflicting name (`measurements-out.csv`), and only then replaces an old one by renaming. Used the same approach for `tar.gz` file.
> Non-conflicting dump archive naming #873

- config/application.rb
- config/elastic_apm.yml
According to [this page](https://www.elastic.co/guide/en/apm/agent/ruby/current/configuration.html),
> There are several ways to configure how Elastic APM behaves. We recommend using a config/elastic_apm.yml file:
> Use config/elastic_apm.yml instead

- Gemfile.lock
- app/assets/javascripts/application.js
In Javascript console when viewing "Safecast Api" page:
```
bootstrap-datetimepicker requires Moment.js to be loaded first
```
> Require moment before bootstrap datetimepicker

- app/models/measurement.rb
- spec/controllers/measurements_controller_spec.rb
Errors like the following were recorded in New Relic:
```
undefined local variable or method `scoped' for #<Class:0x000000000b0c6448> Did you mean? scope unscoped
//var/app/current/app/models/measurement:rb:27:in `nearby_to'
```
`scoped` class method has been deprecated since Rails 5. There was deprecation warning like:
```
DEPRECATION WARNING: Model.scoped is deprecated. Please use Model.all instead.
```
But, we missed it when upgrading to Rails 5.
> Fix error in mesurements#index when only `distance` is specified

- config/newrelic.yml
https://docs.newrelic.com/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration/#error_collector-ignore_errors
> ignore `ActionDispatch::Http::MimeNegotiation::InvalidType` from NewRelic error collector

- app/controllers/bgeigie_imports_controller.rb
- spec/controllers/bgeigie_imports_controller_spec.rb
Currently, HTTP 500 because `beige_imports#show` raises `ActivRecord::RecordNotFound'. https://one.newrelic.com/nr1-core/errors/overview/MTA1NzgxMnxBUE18QVBQTElDQVRJT058MTA1ODAyMjI?account=1057812&duration=604800000&filters=%28domain%3D%27APM%27%20AND%20type%3D%27APPLICATION%27%29&state=718e15f0-37ec-d46d-54bb-4e1bf7914645
> Respond with HTTP 404 when invalid bGeigie import ID is specified

- db/structure.sql
There is no migration for `comments` table.
> :fire: Remove `comments` table

- app/controllers/device_stories_controller.rb
- app/controllers/devices_controller.rb
- app/controllers/users_controller.rb
- spec/controllers/device_stories_controller_spec.rb
- spec/controllers/devices_controller_spec.rb
- spec/controllers/users_controller_spec.rb
Fixes #660
This pull requests uses 'NULLS LAST' that has been standardized since SQL:2003 to order elements with `NULL` values to last instead of assigning default values.
> Order elements with NULL values to last

- app/controllers/bgeigie_imports_controller.rb
- app/controllers/concerns/has_order_scope.rb
- app/controllers/device_stories_controller.rb
- app/controllers/devices_controller.rb
- app/controllers/measurements_controller.rb
- app/controllers/users_controller.rb
- spec/controllers/users_controller_spec.rb
To prevent parameters like:
* `{"order":"captured_at desc) UNION ALL SELECT NULL,NULL,NULL#","locale":"en-US","device_id":"100171"}`
* `{"order":"captured_at desc%' ORDER BY 1#","locale":"en-US","device_id":"100171"}`
> Check value of order filter
